import './scss/base.scss'
import './js/alex.js'
import './js/modalWindow.js'
import "./js/search.js";
import "./scss/search.scss";
import "./scss/fonts.scss";
import './scss/StylemodalWindow.scss'
import './scss/alex.scss'
import './scss/typography.scss'
import './js/timer.js'
import './scss/timer.scss'
