import './js/modalWindow.js'
import './scss/StylemodalWindow.scss'
import './scss/alex.scss'
import './scss/typography.scss'
import './js/timer.js'
import './js/newProducts.js'
import './scss/timer.scss'
import './js/newProducts.js'
